const importanceHeader = 'Is this important to you?';
const questionValues = [
  {
    questionExplanationHeader: 'What is GDPPC?',
    questionExplanationText: 'GDPPC stands for "Gross Domestic Product Per Capita". It is the measurement of the average earning potential for the citizens of that nation.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'GDPPC is often one of the most import factors in determining where one would like to live. It determines your earning potential within that nation and the economic resources that would be made available to you.',
    questionNumber: '1 of 26',
    questionText: 'How important is it that you make as much money as possible?',
    questionFact: 'As of 2019 Luxembourg has the highest GDPPC in the world coming in just over $113,000 per person',
    quality: 'gdp_pc',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  },
  {
    questionExplanationHeader: 'What is GPI?',
    questionExplanationText: 'The Global Peace Index is a yearly report on the level of peace and stability within each nation. It tracks the impacts of violence in nations throughout the world including economic, ecological and political.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'The GPI is a reflection of regional stability and accurately depicts both a governments efforts towards peace as well as foreign intervention.',
    questionNumber: '2 of 26',
    questionText: 'How important is it that you live in a stable region with few drastic social changes?',
    questionFact: 'The average GPI score for the entire planet dropped by 0.34% in 2020.',
    quality: 'gpi_rank_inverse',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
    visual: 'social',
  },
  {
    questionExplanationHeader: 'How does religion factor in?',
    questionExplanationText: 'Religion, regardless of the form plays a major factor into both the political conservatism and law creation of a region.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'The presence of religious conservatism often plays a direct role in regional policy making, social norms and the rights given to both women and minority groups. It is important to weight the volume of religious influence you would like in policy making.',
    questionNumber: '3 of 26',
    questionText: 'How much of the population would you prefer to be non-religious?',
    questionFact: 'Currently the worlds least religious nation is Sweden, with over 83% of the population stating it is unimportant.',
    quality: 'percentage_non_religious',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
    visual: 'social',
  },
  {
    questionExplanationHeader: 'How do you measure happiness?',
    questionExplanationText: 'While happiness is a relatively broad term, this metric takes into account the overall satisfaction of the population as a whole with their position in life.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'While happiness is a good thing to have for the general population, it is also a reflection of the volume of social programs and government assistance. Everyone being happy does not necessarily mean that you will be.',
    questionNumber: '4 of 26',
    questionText: 'How important is the happiness of your neighbors to you?',
    questionFact: 'Finland is the happiest country in the world as of 2019',
    quality: 'happiness_score',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'social',
  },
  {
    questionExplanationHeader: 'Not all college educations are made equal',
    questionExplanationText: 'While most countries in the world offer collegiate level education, those educations often vary greatly in quality.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you want access to an advanced collegiate degree from a highly rated campus for you and your children, this is an important metric for you.',
    questionNumber: '5 of 26',
    questionText: 'How important is it to have access to the worlds top universities?',
    questionFact: 'The majority of the worlds top 100 universities are owned by only 4 nations.',
    quality: 'top_100_universities',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
    visual: 'education',
  },
  {
    questionExplanationHeader: 'How many people should finish college?',
    questionExplanationText: 'While most countries offer college, college is not always accessible to the population. Even in nations with the best colleges in the world, there are huge disparities in who gets to actually attend.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that easy access to college is important, this may be important to you.',
    questionNumber: '6 of 26',
    questionText: 'Is it important that as many people complete college as possible?',
    questionFact: '33% of Americans have a college degree.',
    quality: 'collegiate_completion_rate_top_4',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
    visual: 'education',
  },
  {
    questionExplanationHeader: 'What about high school?',
    questionExplanationText: 'Many nations in the world are still struggling to provide even the base high school education to their people.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that it is the nations job to ensure that as many people graduate high school as possible, this may be important to you.',
    questionNumber: '7 of 26',
    questionText: 'Is it important that as many people graduate high school as possible?',
    questionFact: 'Over 99% of students in South Korea complete their High School education.',
    quality: 'high_school_completion_rate',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
    visual: 'education',
  },
  {
    questionExplanationHeader: 'What is the purpose of high school?',
    questionExplanationText: 'While most nations have a high school education system, they do not all share the same objective. Some nations focus on preparing students for the work force, while others prepare them for college.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that high school should focus on preparing you for work, this is something you probably agree with.',
    questionNumber: '8 of 26',
    questionText: 'Education should focus on preparing you for the work force.',
    questionFact: 'Canada has the highest high school to work force conversion rate in the world!',
    quality: 'top_rated_overall_education',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'education',
  },
  {
    questionExplanationHeader: 'Enjoying local food options',
    questionExplanationText: 'Some cultures pallets are much spicier than others. It is important to factor in your personal culinary taste when deciding where you are going to live!',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you are adverse to spicy food or prefer it, this may be an important question for you.',
    questionNumber: '9 of 26',
    questionText: 'How much do you enjoy spicy food?',
    questionFact: 'Thailand has the spiciest selection of food in the world!',
    quality: 'spiciest_food',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'social',
  },
  {
    questionExplanationHeader: 'Socialist Representation',
    questionExplanationText: 'While there are many nations with socialist representation in government, some have much more than others.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'This question is about political representation preference in government. Most left leaning people will want at least some socialist representation, while many conservatives would prefer none at all.',
    questionNumber: '10 of 26',
    questionText: 'You want to live in a nation with strong socialist representation in government.',
    questionFact: `Socialism: "a political and economic theory of social organization which advocates that the means of production, distribution, and exchange should be owned or regulated by the community as a whole."`,
    quality: 'communist_nation',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'political',
  },
  {
    questionExplanationHeader: 'Do you like to sweat?',
    questionExplanationText: `The nations of the world vary in temperature greatly. The highest summer temperature in Alaska doesn't even reach the lowest temperature in most equatorial nations`,
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: `If you don't like the heat, you will most likely disagree with this question.`,
    questionNumber: '11 of 26',
    questionText: 'You want to live where it is hot.',
    questionFact: '',
    quality: 'most_temperate_nations',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'environment',
  },
  {
    questionExplanationHeader: `How's your selection of jackets?`,
    questionExplanationText: 'While many nations experience cold winters, this question is specifically asking if you would enjoy living in the cold for the majority of the year.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you enjoy being bundled in a jacket and sipping hot drinks, this may be important to you.',
    questionNumber: '12 of 26',
    questionText: 'You want to live where it is cold.',
    questionFact: 'The coldest naturally occurring temperature ever recorder on earth was -67.8°C (-90°F)',
    quality: 'coldest_nations',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'environment',
  },
  {
    questionExplanationHeader: 'Spend time at the beach?',
    questionExplanationText: 'While plenty of nations have coast lines, not all have beaches worth visiting. This question only takes into account the nations with warm, sandy coastline. ',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you see yourself living a life of salty air and sun exposure, this question may be important to you.',
    questionNumber: '13 of 26',
    questionText: 'You want to live near the beach.',
    questionFact: `The beaches of Hawaii are white because of the poop of the Parrot fish. This fish scrapes dead coral and algae to grind up with it's beak, effectively converting dead coral reef into sand.`,
    quality: 'best_beaches',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'environment',
  },
  {
    questionExplanationHeader: `How's your savings?`,
    questionExplanationText: 'Government regulation of an individuals monetary practices is one of the greatest debates of the modern age. Should the individual be completely in charge of determining how the value they produce is spent? How much of a hand should the government have in guiding the free market?',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: `This is a question meant to determine how much you believe the government should be involved in setting laws and policies to guide the "rules and maintenance costs" of the market.`,
    questionNumber: '14 of 26',
    questionText: 'People are generally responsible enough to determine how their money should be used.',
    questionFact: 'Singapore is currently the leading independent nation in economic freedom, with the United States coming in at 6th place.',
    quality: 'highest_economic_freedom',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  },
  {
    questionExplanationHeader: `You've got mail!`,
    questionExplanationText: 'The internet has revolutionized the modern world. It is now the forum for most business, personal and financial interactions on earth. You can day trade on dial up, but you are not going to be able to play video games.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you find yourself using high speed internet often, you will most likely need to live somewhere with a reliable internet connection.',
    questionNumber: '15 of 26',
    questionText: 'Your internet connection needs to be...',
    questionFact: 'While the United States is responsible for the creation of the internet, as of 2020 it has fallen to 15th place in reliability. Taiwan currently has the most reliable internet infrastructure.',
    quality: 'best_internet_infrastructure',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Somewhat Reliable',
    rightVal: 'Always Reliable',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  },
  {
    questionExplanationHeader: 'MMM... Cozy',
    questionExplanationText: 'Some nations like Japan are so dense that they have to build infrastructure vertically, while Mongolia is 2/3 the width of China with only 3.17 million inhabitants',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you would like to live in a densely populated city, you most likely agree with this question.',
    questionNumber: '16 of 26',
    questionText: 'You want to live somewhere with a lot of people in one place.',
    questionFact: 'Monaco has the worlds highest population density with 26,150 people per square kilometer.',
    quality: 'high_pop_density',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'environment',
  },
  {
    questionExplanationHeader: 'Who should own the means of production?',
    questionExplanationText: 'This question is asking what percentage of the economy you believe the government should subsidize.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that the government should produce a larger percentage of the nations economy, you most likely agree with this.',
    questionNumber: '17 of 26',
    questionText: 'The government should buy into and subsidize the economy.',
    questionFact: 'The Chinese government owns over 96% of their economies enterprises.',
    quality: 'gov_subsidies_percentage',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  },
  {
    questionExplanationHeader: `Should the rich invest in businesses or the government?`,
    questionExplanationText: 'This question is asking what you believe the top margin of earners in a nation should be taxed. This does not necessarily impact the tax rate of the middle and lower class earners.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that the wealthiest members of a nation should pay the largest share to maintain the government, you most likely agree with this.',
    questionNumber: '18 of 26',
    questionText: 'The rich should be heavily taxed.',
    questionFact: 'Sweden has the highest top marginal tax rate in the world at 78%!',
    quality: 'top_margin_tax_rate',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  },
  {
    questionExplanationHeader: 'How much land and property does the government need?',
    questionExplanationText: 'This is a question of state land ownership. Do you believe that the government should own and maintain a large amount of the nations land and property assets?',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that the majority of land ownership should be in the hands of individuals, you most likely disagree with this.',
    questionNumber: '19 of 26',
    questionText: 'The government should own property and financial assets.',
    questionFact: 'The United States government owns 28% of the nations land or 640 million of its 2.27 billion acres',
    quality: 'state_asset_ownership',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  },
  {
    questionExplanationHeader: 'State Workers',
    questionExplanationText: 'In order to maintain the land and services owned by a government a certain level of the population has to be employed by the state. This question is taking into account the percentage of the population you believe should be employed by the state.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that the government should employ as few people as possible, set the slider to 0.',
    questionNumber: '20 of 26',
    questionText: 'What percentage of national employment should be provided by the government?',
    questionFact: `30% of Norway's population works for the government.`,
    quality: 'size_of_gov',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: '0%',
    rightVal: '100%',
    className: 'sliderInput',
    value: 50,
    visual: 'political',
  },
  {
    questionExplanationHeader: 'Constitutional Continuity',
    questionExplanationText: 'This is a question of judicial independence. This is defined by the level of separation the court system maintains from the other branches of government.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that politics are often too volatile to allow the government a direct hand in the court system, you most likely agree with this. If you believe more strongly that the judicial system should change to match the character of the nation in its current state, you may disagree.',
    questionNumber: '21 of 26',
    questionText: 'The court system should be impartial and un influenced by politics.',
    questionFact: 'In the United States federal judges serve a life term. The lifetime is intended to provide job security, and allow appointed judges to do what is right under the law, because they don’t have to fear that they will be fired if they make an unpopular decision.',
    quality: 'judicial_independence',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'political',
  },
  {
    questionExplanationHeader: 'Military Police',
    questionExplanationText: 'This question is asking whether you believe the local military should have an involvement in policing the population. Do you believe this creates a safer or more dangerous environment?',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'This question is important to you if you have strong feelings about federal government involvement in regional policing matters. Would you feel safer with a military presence in the city you are in or intimidated?',
    questionNumber: '22 of 26',
    questionText: 'The military should assist in policing the population.',
    questionFact: 'MP\'s provide security services on military bases around the world. They also conduct law enforcement functions and take on investigations of minor crimes. Military police perform patrol duties, make arrests and enforce military law.',
    quality: 'law_enf_mil_interference',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'political',
  },
  {
    questionExplanationHeader: 'Should there be rules to what can be sold and how things are sold?',
    questionExplanationText: 'This question asks if you believe that there should be government involvement in the transactions and sales that take place within a nations borders. Should there be a hefty regulations on how a home is sold? Should the government prevent the sale of certain products that they consider bad for the population?',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: `If the thought of having to fill out extensive paper work, inspections and government fees to purchase a house bothers you, you may want less regulation.`,
    questionNumber: '23 of 26',
    questionText: 'The government should regulate the sale of properties.',
    questionFact: 'The United States FDA banned the sale and interstate transportation of milk in 1987.',
    quality: 'prop_sale_reg',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Less Regulation',
    rightVal: 'More Regulation',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  },
  {
    questionExplanationHeader: 'How should we maintain order?',
    questionExplanationText: 'This is a question about police and law enforcement. Would your ideal police force be well maintained and trained? Do you think funds should be put elsewhere to reduce the need for law enforcement?',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that well trained and well payed officers are the key to a peaceful community you may agree with this.',
    questionNumber: '24 of 26',
    questionText: 'Law enforcement should be a highly trained and well paid organization.',
    questionFact: 'Hungary spends more than any other nation on its police force at 1.4% of its gross domestic product per year.',
    quality: 'police_reliability',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'political',
  },
  {
    questionExplanationHeader: 'Should you be encouraged to buy locally?',
    questionExplanationText: 'Governments will often create tariffs to reduce the volume of goods traded between themselves and other countries. Tariffs are import and export taxes imposed on goods moving between national borders.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that the government should not try to impose its ideals on goods traded freely between its borders, you may disagree with this.',
    questionNumber: '25 of 26',
    questionText: 'Imports and exports need to be heavily taxed.',
    questionFact: 'Iran has the 3rd highest import tariff in the world at 20.92%',
    quality: 'foreign_trade_tariff',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'political',
  },
  {
    questionExplanationHeader: `You can't fire me, I quit!`,
    questionExplanationText: 'This question measures how much you believe the government should be involved in encouraging hiring of certain groups and setting regulations against when an employer can and cannot fire an employee.',
    whyIsThisImportantHeader: importanceHeader,
    whyIsThisImportText: 'If you believe that there should be many protections in place against wrongful termination of employment you may agree, while if you believe that an employer should have complete control over who they have working in their business, you may disagree.',
    questionNumber: '26 of 26',
    questionText: 'There should be regulations determining when someone can or cannot be fired.',
    questionFact: 'At-Will employment disclaimers are not valid in the state of South Carolina unless they are printed on the cover page of employee handbooks in underlined capital letters.',
    quality: 'hiring_firing_reg',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
    visual: 'economic',
  }
];
export default questionValues;