const questionValues = [
  {
    text: 'How important is it that you make as much money as possible',
    quality: 'gdp_pc',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'It is important to me that the government I live under values peace above all things.',
    quality: 'gpi_rank_inverse',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'It is important that I live in a nation with as few religious people as possible.',
    quality: 'percentage_non_religious',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want everyone around me to be as happy as possible.',
    quality: 'happiness_score',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'It is important that I live where my children have access to the worlds best universities',
    quality: 'top_100_universities',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'It is important that as many people complete college as possible.',
    quality: 'collegiate_completion_rate_top_4',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'It is important that as many people graduate high school as possible.',
    quality: 'high_school_completion_rate',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Not Important',
    rightVal: 'Very Important',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'The quality of education a nation can provide is very important.',
    quality: 'top_rated_overall_education',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I enjoy very spicy food.',
    quality: 'spiciest_food',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want to live in a nation with strong anti-capitalist (or communist) representation in government.',
    quality: 'communist_nation',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want to live where it is hot.',
    quality: 'most_temperate_nations',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want to live where it is cold.',
    quality: 'coldest_nations',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want to live near the beach.',
    quality: 'best_beaches',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I am responsible enough to determine where and when I work and how I invest my money.',
    quality: 'highest_economic_freedom',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'My internet connectivity needs to be....',
    quality: 'best_internet_infrastructure',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Somewhat Reliable',
    rightVal: 'Always Reliable',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want to live somewhere with a lot of people in one place.',
    quality: 'high_pop_density',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'The government should buy into and subsidize the economy.',
    quality: 'gov_subsidies_percentage',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'The rich should be heavily taxed.',
    quality: 'top_margin_tax_rate',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'The government should own property and financial assets.',
    quality: 'state_asset_ownership',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want to live somewhere with many government jobs available.',
    quality: 'size_of_gov',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'The court system should not be influenced by politics.',
    quality: 'judicial_independence',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'The military should assist in policing the population.',
    quality: 'law_enf_mil_interference',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'There needs to be regulations on property sales.',
    quality: 'prop_sale_reg',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Less Regulation',
    rightVal: 'More Regulation',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'I want fast and effective responses from local law enforcement.',
    quality: 'police_reliability',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'Imports and exports need to be heavily taxed.',
    quality: 'foreign_trade_tariff',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  },
  {
    text: 'There should be regulations determining when someone can and cannot be fired.',
    quality: 'hiring_firing_reg',
    inputType: 'range',
    inputReference: 'qSlider',
    leftVal: 'Strongly Disagree',
    rightVal: 'Strongly Agree',
    className: 'sliderInput',
    value: 50,
  }
];
export default questionValues;