
create TABLE `where_to_final` IF NOT EXISTS (
`index` TEXT NULL,
`iso` TEXT NULL,
`country` TEXT NULL,
`gdp_pc` TEXT NULL,
`gpi_rank_inverse` TEXT NULL,
`percentage_non_religious` TEXT NULL,
`happiness_score` TEXT NULL,
`top_100_universities` TEXT NULL,
`collegiate_completion_rate_top_4` TEXT NULL,
`high_school_completion_rate` TEXT NULL,
`top_rated_overall_education` TEXT NULL,
`spiciest_food` TEXT NULL,
`communist_nation` TEXT NULL,
`most_temperate_nations` TEXT NULL,
`coldest_nations` TEXT NULL,
`best_beaches` TEXT NULL,
`highest_economic_freedom` TEXT NULL,
`best_internet_infrastructure` TEXT NULL,
`high_pop_density` TEXT NULL,
`gov_subsidies_percentage` TEXT NULL,
`top_margin_tax_rate` TEXT NULL,
`state_asset_ownership` TEXT NULL,
`size_of_gov` TEXT NULL,
`judicial_independence` TEXT NULL,
`law_enf_mil_interference` TEXT NULL,
`prop_sale_reg` TEXT NULL,
`police_reliability` TEXT NULL,
`foreign_trade_tarrif` TEXT NULL,
`hiring_firing_reg` TEXT NULL
);



//values start here

1,
AGO,
Angola,
8200,
64,
0.3,
3.795,
0,
0,
0,
0,
0,
0,
0,
0,
0,
4.83,
0,
0,
8.89,
10,
10,
6.76,
1.44,
3.33,
5.49,
3.36,
7.07,
4.4,