import React from 'react';

const CountryData =
  [
    {
      country: 'A',
      gdp_pc: 'a',
      gpi_rank: 'a',
      percentage_non_religious: 'a',
      happiness_score: 'a',
      top_100_universities: 'a',
      collegiate_completion_rate_top_: 'a',
      high_school_completion_rate: 'a',
      top_rated_overall_education: 'a',
      spiciest_food: 'a',
      communist_nation: 'a',
      most_temperate_nations: 'a',
      coldest_nations: 'a',
      best_beaches: 'a',
      high_economic_freedom: 'a',
      best_health_care: 'a',
      best_internet_infrastructure: 'a',
      highest_pop_density: 'a',
      least_corrupt: 'a',
    },
    {
      country: 'B',
      gdp_pc: '',
      gpi_rank: '',
      percentage_non_religious: '',
      happiness_score: '',
      top_100_universities: '',
      collegiate_completion_rate_top_: '',
      high_school_completion_rate: '',
      top_rated_overall_education: '',
      spiciest_food: '',
      communist_nation: '',
      most_temperate_nations: '',
      coldest_nations: '',
      best_beaches: '',
      high_economic_freedom: '',
      best_health_care: '',
      best_internet_infrastructure: '',
      highest_pop_density: '',
      least_corrupt: '',
    },
    {
      country: 'C',
      gdp_pc: '',
      gpi_rank: '',
      percentage_non_religious: '',
      happiness_score: '',
      top_100_universities: '',
      collegiate_completion_rate_top_: '',
      high_school_completion_rate: '',
      top_rated_overall_education: '',
      spiciest_food: '',
      communist_nation: '',
      most_temperate_nations: '',
      coldest_nations: '',
      best_beaches: '',
      high_economic_freedom: '',
      best_health_care: '',
      best_internet_infrastructure: '',
      highest_pop_density: '',
      least_corrupt: '',
    },


  ];

export default CountryData;